// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/y0ug/codehaven/internal/filemanager (interfaces: FileManager)
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=filemanager . FileManager
//

// Package filemanager is a generated GoMock package.
package filemanager

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockFileManager is a mock of FileManager interface.
type MockFileManager struct {
	ctrl     *gomock.Controller
	recorder *MockFileManagerMockRecorder
	isgomock struct{}
}

// MockFileManagerMockRecorder is the mock recorder for MockFileManager.
type MockFileManagerMockRecorder struct {
	mock *MockFileManager
}

// NewMockFileManager creates a new mock instance.
func NewMockFileManager(ctrl *gomock.Controller) *MockFileManager {
	mock := &MockFileManager{ctrl: ctrl}
	mock.recorder = &MockFileManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileManager) EXPECT() *MockFileManagerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFileManager) Add(path string, readOnly bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", path, readOnly)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockFileManagerMockRecorder) Add(path, readOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFileManager)(nil).Add), path, readOnly)
}

// Commit mocks base method.
func (m *MockFileManager) Commit(msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockFileManagerMockRecorder) Commit(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockFileManager)(nil).Commit), msg)
}

// Get mocks base method.
func (m *MockFileManager) Get(path string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockFileManagerMockRecorder) Get(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileManager)(nil).Get), path)
}

// GetFileLastUpdate mocks base method.
func (m *MockFileManager) GetFileLastUpdate(path string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileLastUpdate", path)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileLastUpdate indicates an expected call of GetFileLastUpdate.
func (mr *MockFileManagerMockRecorder) GetFileLastUpdate(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileLastUpdate", reflect.TypeOf((*MockFileManager)(nil).GetFileLastUpdate), path)
}

// GetFileStatus mocks base method.
func (m *MockFileManager) GetFileStatus(path string) (FileStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileStatus", path)
	ret0, _ := ret[0].(FileStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileStatus indicates an expected call of GetFileStatus.
func (mr *MockFileManagerMockRecorder) GetFileStatus(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileStatus", reflect.TypeOf((*MockFileManager)(nil).GetFileStatus), path)
}

// GetNewFiles mocks base method.
func (m *MockFileManager) GetNewFiles() map[string]*FileInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewFiles")
	ret0, _ := ret[0].(map[string]*FileInfo)
	return ret0
}

// GetNewFiles indicates an expected call of GetNewFiles.
func (mr *MockFileManagerMockRecorder) GetNewFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewFiles", reflect.TypeOf((*MockFileManager)(nil).GetNewFiles))
}

// HasFileChanged mocks base method.
func (m *MockFileManager) HasFileChanged(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFileChanged", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasFileChanged indicates an expected call of HasFileChanged.
func (mr *MockFileManagerMockRecorder) HasFileChanged(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFileChanged", reflect.TypeOf((*MockFileManager)(nil).HasFileChanged), path)
}

// IsFileReadOnly mocks base method.
func (m *MockFileManager) IsFileReadOnly(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFileReadOnly", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFileReadOnly indicates an expected call of IsFileReadOnly.
func (mr *MockFileManagerMockRecorder) IsFileReadOnly(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFileReadOnly", reflect.TypeOf((*MockFileManager)(nil).IsFileReadOnly), path)
}

// List mocks base method.
func (m *MockFileManager) List(filters FileFilters) map[string]*FileInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", filters)
	ret0, _ := ret[0].(map[string]*FileInfo)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockFileManagerMockRecorder) List(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFileManager)(nil).List), filters)
}

// MarkFileAsSent mocks base method.
func (m *MockFileManager) MarkFileAsSent(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFileAsSent", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFileAsSent indicates an expected call of MarkFileAsSent.
func (mr *MockFileManagerMockRecorder) MarkFileAsSent(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFileAsSent", reflect.TypeOf((*MockFileManager)(nil).MarkFileAsSent), path)
}

// Remove mocks base method.
func (m *MockFileManager) Remove(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFileManagerMockRecorder) Remove(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFileManager)(nil).Remove), path)
}

// Write mocks base method.
func (m *MockFileManager) Write(path, newContent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", path, newContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockFileManagerMockRecorder) Write(path, newContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFileManager)(nil).Write), path, newContent)
}
