// Code generated by go generate; DO NOT EDIT.
package prompts


type Prompter interface {
   GetName() string
   GetSystemReminder() string
   GetFilesContentGPTEdits() string
   GetFilesContentGPTEditsNoRepo() string
   GetFilesContentGPTNoEdits() string
   GetFilesContentLocalEdits() string
   GetLazyPrompt() string
   GetExampleMessages() []Message
   GetFilesContentPrefix() string
   GetFilesContentAssistantReply() string
   GetFilesNoFullFiles() string
   GetFilesNoFullFilesWithRepoMap() string
   GetFilesNoFullFilesWithRepoMapReply() string
   GetRepoContentPrefix() string
   GetReadOnlyFilesPrefix() string
   GetShellCmdPrompt() string
   GetShellCmdReminder() string
   GetNoShellCmdPrompt() string
   GetNoShellCmdReminder() string
   GetMainSystem() string
   GetRedactedEditMessage() string
   GetEditFormat() string
}


// Implementing interface Prompter for BasePrompts
func (p *BasePrompts) GetName() string {
    return p.Name
}
func (p *BasePrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *BasePrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *BasePrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *BasePrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *BasePrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *BasePrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *BasePrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *BasePrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *BasePrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *BasePrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *BasePrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *BasePrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *BasePrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *BasePrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *BasePrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *BasePrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *BasePrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *BasePrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *BasePrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *BasePrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *BasePrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for EditBlockFencedPrompts
func (p *EditBlockFencedPrompts) GetName() string {
    return p.Name
}
func (p *EditBlockFencedPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *EditBlockFencedPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *EditBlockFencedPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *EditBlockFencedPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *EditBlockFencedPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *EditBlockFencedPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *EditBlockFencedPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *EditBlockFencedPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *EditBlockFencedPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *EditBlockFencedPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *EditBlockFencedPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *EditBlockFencedPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *EditBlockFencedPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *EditBlockFencedPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *EditBlockFencedPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *EditBlockFencedPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *EditBlockFencedPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *EditBlockFencedPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *EditBlockFencedPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *EditBlockFencedPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *EditBlockFencedPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for HelpPrompts
func (p *HelpPrompts) GetName() string {
    return p.Name
}
func (p *HelpPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *HelpPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *HelpPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *HelpPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *HelpPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *HelpPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *HelpPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *HelpPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *HelpPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *HelpPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *HelpPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *HelpPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *HelpPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *HelpPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *HelpPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *HelpPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *HelpPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *HelpPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *HelpPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *HelpPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *HelpPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for EditorWholeFilePrompts
func (p *EditorWholeFilePrompts) GetName() string {
    return p.Name
}
func (p *EditorWholeFilePrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *EditorWholeFilePrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *EditorWholeFilePrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *EditorWholeFilePrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *EditorWholeFilePrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *EditorWholeFilePrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *EditorWholeFilePrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *EditorWholeFilePrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *EditorWholeFilePrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *EditorWholeFilePrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *EditorWholeFilePrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *EditorWholeFilePrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *EditorWholeFilePrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *EditorWholeFilePrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *EditorWholeFilePrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *EditorWholeFilePrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *EditorWholeFilePrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *EditorWholeFilePrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *EditorWholeFilePrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *EditorWholeFilePrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *EditorWholeFilePrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for SingleWholeFileFunctionPrompts
func (p *SingleWholeFileFunctionPrompts) GetName() string {
    return p.Name
}
func (p *SingleWholeFileFunctionPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *SingleWholeFileFunctionPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *SingleWholeFileFunctionPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *SingleWholeFileFunctionPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *SingleWholeFileFunctionPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *SingleWholeFileFunctionPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *SingleWholeFileFunctionPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *SingleWholeFileFunctionPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *SingleWholeFileFunctionPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *SingleWholeFileFunctionPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *SingleWholeFileFunctionPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *SingleWholeFileFunctionPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *SingleWholeFileFunctionPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *SingleWholeFileFunctionPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *SingleWholeFileFunctionPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *SingleWholeFileFunctionPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *SingleWholeFileFunctionPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *SingleWholeFileFunctionPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *SingleWholeFileFunctionPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *SingleWholeFileFunctionPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *SingleWholeFileFunctionPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for UdiffPrompts
func (p *UdiffPrompts) GetName() string {
    return p.Name
}
func (p *UdiffPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *UdiffPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *UdiffPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *UdiffPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *UdiffPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *UdiffPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *UdiffPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *UdiffPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *UdiffPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *UdiffPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *UdiffPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *UdiffPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *UdiffPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *UdiffPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *UdiffPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *UdiffPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *UdiffPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *UdiffPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *UdiffPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *UdiffPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *UdiffPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for ArchitectPrompts
func (p *ArchitectPrompts) GetName() string {
    return p.Name
}
func (p *ArchitectPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *ArchitectPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *ArchitectPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *ArchitectPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *ArchitectPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *ArchitectPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *ArchitectPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *ArchitectPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *ArchitectPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *ArchitectPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *ArchitectPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *ArchitectPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *ArchitectPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *ArchitectPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *ArchitectPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *ArchitectPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *ArchitectPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *ArchitectPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *ArchitectPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *ArchitectPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *ArchitectPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for AskPrompts
func (p *AskPrompts) GetName() string {
    return p.Name
}
func (p *AskPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *AskPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *AskPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *AskPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *AskPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *AskPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *AskPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *AskPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *AskPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *AskPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *AskPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *AskPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *AskPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *AskPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *AskPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *AskPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *AskPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *AskPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *AskPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *AskPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *AskPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for EditBlockPrompts
func (p *EditBlockPrompts) GetName() string {
    return p.Name
}
func (p *EditBlockPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *EditBlockPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *EditBlockPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *EditBlockPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *EditBlockPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *EditBlockPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *EditBlockPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *EditBlockPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *EditBlockPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *EditBlockPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *EditBlockPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *EditBlockPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *EditBlockPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *EditBlockPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *EditBlockPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *EditBlockPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *EditBlockPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *EditBlockPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *EditBlockPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *EditBlockPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *EditBlockPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for EditBlockFunctionPrompts
func (p *EditBlockFunctionPrompts) GetName() string {
    return p.Name
}
func (p *EditBlockFunctionPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *EditBlockFunctionPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *EditBlockFunctionPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *EditBlockFunctionPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *EditBlockFunctionPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *EditBlockFunctionPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *EditBlockFunctionPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *EditBlockFunctionPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *EditBlockFunctionPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *EditBlockFunctionPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *EditBlockFunctionPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *EditBlockFunctionPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *EditBlockFunctionPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *EditBlockFunctionPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *EditBlockFunctionPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *EditBlockFunctionPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *EditBlockFunctionPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *EditBlockFunctionPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *EditBlockFunctionPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *EditBlockFunctionPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *EditBlockFunctionPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for EditorEditBlockPrompts
func (p *EditorEditBlockPrompts) GetName() string {
    return p.Name
}
func (p *EditorEditBlockPrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *EditorEditBlockPrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *EditorEditBlockPrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *EditorEditBlockPrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *EditorEditBlockPrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *EditorEditBlockPrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *EditorEditBlockPrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *EditorEditBlockPrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *EditorEditBlockPrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *EditorEditBlockPrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *EditorEditBlockPrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *EditorEditBlockPrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *EditorEditBlockPrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *EditorEditBlockPrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *EditorEditBlockPrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *EditorEditBlockPrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *EditorEditBlockPrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *EditorEditBlockPrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *EditorEditBlockPrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *EditorEditBlockPrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *EditorEditBlockPrompts) GetEditFormat() string {
    return p.EditFormat
}

// Implementing interface Prompter for WholeFilePrompts
func (p *WholeFilePrompts) GetName() string {
    return p.Name
}
func (p *WholeFilePrompts) GetSystemReminder() string {
    return p.SystemReminder
}
func (p *WholeFilePrompts) GetFilesContentGPTEdits() string {
    return p.FilesContentGPTEdits
}
func (p *WholeFilePrompts) GetFilesContentGPTEditsNoRepo() string {
    return p.FilesContentGPTEditsNoRepo
}
func (p *WholeFilePrompts) GetFilesContentGPTNoEdits() string {
    return p.FilesContentGPTNoEdits
}
func (p *WholeFilePrompts) GetFilesContentLocalEdits() string {
    return p.FilesContentLocalEdits
}
func (p *WholeFilePrompts) GetLazyPrompt() string {
    return p.LazyPrompt
}
func (p *WholeFilePrompts) GetExampleMessages() []Message {
    return p.ExampleMessages
}
func (p *WholeFilePrompts) GetFilesContentPrefix() string {
    return p.FilesContentPrefix
}
func (p *WholeFilePrompts) GetFilesContentAssistantReply() string {
    return p.FilesContentAssistantReply
}
func (p *WholeFilePrompts) GetFilesNoFullFiles() string {
    return p.FilesNoFullFiles
}
func (p *WholeFilePrompts) GetFilesNoFullFilesWithRepoMap() string {
    return p.FilesNoFullFilesWithRepoMap
}
func (p *WholeFilePrompts) GetFilesNoFullFilesWithRepoMapReply() string {
    return p.FilesNoFullFilesWithRepoMapReply
}
func (p *WholeFilePrompts) GetRepoContentPrefix() string {
    return p.RepoContentPrefix
}
func (p *WholeFilePrompts) GetReadOnlyFilesPrefix() string {
    return p.ReadOnlyFilesPrefix
}
func (p *WholeFilePrompts) GetShellCmdPrompt() string {
    return p.ShellCmdPrompt
}
func (p *WholeFilePrompts) GetShellCmdReminder() string {
    return p.ShellCmdReminder
}
func (p *WholeFilePrompts) GetNoShellCmdPrompt() string {
    return p.NoShellCmdPrompt
}
func (p *WholeFilePrompts) GetNoShellCmdReminder() string {
    return p.NoShellCmdReminder
}
func (p *WholeFilePrompts) GetMainSystem() string {
    return p.MainSystem
}
func (p *WholeFilePrompts) GetRedactedEditMessage() string {
    return p.RedactedEditMessage
}
func (p *WholeFilePrompts) GetEditFormat() string {
    return p.EditFormat
}