// main.go
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"text/template"
)

const headerText = `// Code generated by go generate; DO NOT EDIT.
package prompts
`

const templateGetter = `

// Implementing interface {{.InterfaceName}} for {{.StructName}}
{{- range .Methods}}
func (p *{{$.StructName}}) {{.MethodName}}() {{.RetType}} {
    return p.{{.FieldName}}
}
{{- end}}`

const templateInterfaceMethod = `
type {{.InterfaceName}} interface {
   {{- range .Methods}}
   {{.MethodName}}() {{.RetType}}
   {{- end}}
}
`

type StructField struct {
	StructName string
	RetType    string
	FieldName  string
}

type StructsDef map[string][]StructField

type InterfaceMethodData struct {
	InterfaceName string
	RetType       string
	FieldName     string
	MethodName    string
}

type InterfacesDef map[string][]InterfaceMethodData

func main() {
	filenames := []string{
		"types.go",
	}

	// Create output file
	f, err := os.Create("generated_prompts.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	// Create templateGetter
	tmplGetter, err := template.New("templateGetter").Parse(templateGetter)
	if err != nil {
		fmt.Printf("Error parsing template: %v\n", err)
	}

	tmplInterfaceMethod, err := template.New("templateGetter").Parse(templateInterfaceMethod)
	if err != nil {
		fmt.Printf("Error parsing template: %v\n", err)
	}

	fmt.Fprintf(f, "%s\n", headerText)

	for _, filename := range filenames {
		log.Printf("Parsing file %s\n", filename)
		structsDef, InterfacesDef := parseFile(filename)
		fmt.Printf("Found %d structs and %d interfaces\n", len(structsDef), len(InterfacesDef))
		if basePrompt, ok := structsDef["BasePrompts"]; ok {
			methods := make([]InterfaceMethodData, 0)
			interfaceName := "Prompter"
			for _, d := range basePrompt {
				mehotd := InterfaceMethodData{
					InterfaceName: interfaceName,
					RetType:       d.RetType,
					MethodName:    "Get" + d.FieldName,
					FieldName:     d.FieldName,
				}
				methods = append(methods, mehotd)
			}
			data := struct {
				InterfaceName string
				StructName    string
				Methods       []InterfaceMethodData
			}{
				InterfaceName: interfaceName,
				Methods:       methods,
			}

			// Generate the interace methods
			tmplInterfaceMethod.Execute(f, data)

			// Generate the getters for the struct that finish with Prompts
			for structName := range structsDef {
				if strings.HasSuffix(structName, "Prompts") {
					data.StructName = structName
					log.Printf("Generating getters for struct %s %v\n", structName, data.Methods)
					tmplGetter.Execute(f, data)
				}
			}
		}
		// if promptInterface, ok := InterfacesDef["Prompts"]; !ok {
		// }
	}

	// tmpl.Execute(f, d)
}

func parseFile(filename string) (StructsDef, InterfacesDef) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		log.Printf("Error parsing file %s: %v\n", filename, err)
		return nil, nil
	}

	return extractDef(node)
}

// Extract all the struct fields that end with Prompts
// Not used
func extractDef(node *ast.File) (StructsDef, InterfacesDef) {
	structsDef := make(StructsDef, 0)
	interfacesDef := make(InterfacesDef, 0)

	// Find struct declarations
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range genDecl.Specs {
			spec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			specName := spec.Name.Name
			switch spec := spec.Type.(type) {
			case *ast.StructType:

				// Generate getter data for the struct fields that finish with Prompts
				data := getStructDef(specName, spec)
				if len(structsDef[specName]) == 0 {
					structsDef[specName] = make([]StructField, 0)
				}
				structsDef[specName] = append(structsDef[specName], data...)

			case *ast.InterfaceType:
				// Generate getter data for the struct fields that finish with Prompts
				data := getInterfaceDef(specName, spec)
				if len(interfacesDef[specName]) == 0 {
					interfacesDef[specName] = make([]InterfaceMethodData, 0)
				}
				interfacesDef[specName] = append(interfacesDef[specName], data...)
			}

		}
	}
	return structsDef, interfacesDef
}

// Extract Interface function information
// Not used
func getInterfaceDef(
	interfaceName string,
	interfaceType *ast.InterfaceType,
) []InterfaceMethodData {
	var results []InterfaceMethodData

	for _, method := range interfaceType.Methods.List {
		funcType := method.Type.(*ast.FuncType)
		// Extract return type
		retType := string(getFieldType(funcType.Results.List[0].Type))
		// Extract method name
		methodName := method.Names[0].Name
		// Convert GetXXX to XXX for field name
		fieldName := strings.TrimPrefix(methodName, "Get")

		data := InterfaceMethodData{
			InterfaceName: interfaceName,
			RetType:       retType,
			MethodName:    methodName,
			FieldName:     fieldName,
		}
		results = append(results, data)
	}
	return results
}

func getStructDef(structName string, structType *ast.StructType) []StructField {
	results := make([]StructField, 0)

	for _, field := range structType.Fields.List {
		// Skip fields without names
		if len(field.Names) == 0 {
			continue
		}

		fieldName := field.Names[0].Name
		// Skip if field starts with lowercase (private)
		if !ast.IsExported(fieldName) {
			continue
		}

		// Check if field has gen:"getter" tag
		// if field.Tag != nil {
		// 	tag := strings.Trim(field.Tag.Value, "`")
		// 	if !strings.Contains(tag, `gen:"getter"`) {
		// 		continue
		// 	}
		// }

		// Get the field type as string
		fieldType := string(getFieldType(field.Type))

		data := StructField{FieldName: fieldName, RetType: fieldType, StructName: structName}
		log.Printf("%v\n", data)
		results = append(results, data)
	}
	return results
}

func getFieldType(expr ast.Expr) []byte {
	switch t := expr.(type) {
	case *ast.Ident:
		return []byte(t.Name)
	case *ast.StarExpr:
		return append([]byte("*"), getFieldType(t.X)...)
	case *ast.SelectorExpr:
		return append(append(getFieldType(t.X), '.'), []byte(t.Sel.Name)...)
	case *ast.ArrayType:
		return append([]byte("[]"), getFieldType(t.Elt)...)
	default:
		return []byte(fmt.Sprintf("%T", expr))
	}
}
