// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/y0ug/codehaven/internal/gitrepo (interfaces: GitRepoInterface,IOInterface)
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=gitrepo . GitRepoInterface,IOInterface
//

// Package gitrepo is a generated GoMock package.
package gitrepo

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitRepoInterface is a mock of GitRepoInterface interface.
type MockGitRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepoInterfaceMockRecorder
	isgomock struct{}
}

// MockGitRepoInterfaceMockRecorder is the mock recorder for MockGitRepoInterface.
type MockGitRepoInterfaceMockRecorder struct {
	mock *MockGitRepoInterface
}

// NewMockGitRepoInterface creates a new mock instance.
func NewMockGitRepoInterface(ctrl *gomock.Controller) *MockGitRepoInterface {
	mock := &MockGitRepoInterface{ctrl: ctrl}
	mock.recorder = &MockGitRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepoInterface) EXPECT() *MockGitRepoInterfaceMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockGitRepoInterface) Commit(fnames []string, context, message string, aiderEdits bool) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", fnames, context, message, aiderEdits)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Commit indicates an expected call of Commit.
func (mr *MockGitRepoInterfaceMockRecorder) Commit(fnames, context, message, aiderEdits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockGitRepoInterface)(nil).Commit), fnames, context, message, aiderEdits)
}

// GetDiffs mocks base method.
func (m *MockGitRepoInterface) GetDiffs(fnames []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiffs", fnames)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiffs indicates an expected call of GetDiffs.
func (mr *MockGitRepoInterfaceMockRecorder) GetDiffs(fnames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiffs", reflect.TypeOf((*MockGitRepoInterface)(nil).GetDiffs), fnames)
}

// GetHeadCommitMessage mocks base method.
func (m *MockGitRepoInterface) GetHeadCommitMessage(defaultMsg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeadCommitMessage", defaultMsg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeadCommitMessage indicates an expected call of GetHeadCommitMessage.
func (mr *MockGitRepoInterfaceMockRecorder) GetHeadCommitMessage(defaultMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeadCommitMessage", reflect.TypeOf((*MockGitRepoInterface)(nil).GetHeadCommitMessage), defaultMsg)
}

// GetHeadCommitSHA mocks base method.
func (m *MockGitRepoInterface) GetHeadCommitSHA(short bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeadCommitSHA", short)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeadCommitSHA indicates an expected call of GetHeadCommitSHA.
func (mr *MockGitRepoInterfaceMockRecorder) GetHeadCommitSHA(short any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeadCommitSHA", reflect.TypeOf((*MockGitRepoInterface)(nil).GetHeadCommitSHA), short)
}

// IsDirty mocks base method.
func (m *MockGitRepoInterface) IsDirty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDirty indicates an expected call of IsDirty.
func (mr *MockGitRepoInterfaceMockRecorder) IsDirty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirty", reflect.TypeOf((*MockGitRepoInterface)(nil).IsDirty))
}

// IsFileDirty mocks base method.
func (m *MockGitRepoInterface) IsFileDirty(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFileDirty", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFileDirty indicates an expected call of IsFileDirty.
func (mr *MockGitRepoInterfaceMockRecorder) IsFileDirty(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFileDirty", reflect.TypeOf((*MockGitRepoInterface)(nil).IsFileDirty), path)
}

// IsIgnoredFile mocks base method.
func (m *MockGitRepoInterface) IsIgnoredFile(fname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIgnoredFile", fname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsIgnoredFile indicates an expected call of IsIgnoredFile.
func (mr *MockGitRepoInterfaceMockRecorder) IsIgnoredFile(fname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIgnoredFile", reflect.TypeOf((*MockGitRepoInterface)(nil).IsIgnoredFile), fname)
}

// PathInRepo mocks base method.
func (m *MockGitRepoInterface) PathInRepo(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathInRepo", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PathInRepo indicates an expected call of PathInRepo.
func (mr *MockGitRepoInterfaceMockRecorder) PathInRepo(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathInRepo", reflect.TypeOf((*MockGitRepoInterface)(nil).PathInRepo), path)
}

// MockIOInterface is a mock of IOInterface interface.
type MockIOInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIOInterfaceMockRecorder
	isgomock struct{}
}

// MockIOInterfaceMockRecorder is the mock recorder for MockIOInterface.
type MockIOInterfaceMockRecorder struct {
	mock *MockIOInterface
}

// NewMockIOInterface creates a new mock instance.
func NewMockIOInterface(ctrl *gomock.Controller) *MockIOInterface {
	mock := &MockIOInterface{ctrl: ctrl}
	mock.recorder = &MockIOInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOInterface) EXPECT() *MockIOInterfaceMockRecorder {
	return m.recorder
}

// ToolError mocks base method.
func (m *MockIOInterface) ToolError(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToolError", msg)
}

// ToolError indicates an expected call of ToolError.
func (mr *MockIOInterfaceMockRecorder) ToolError(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolError", reflect.TypeOf((*MockIOInterface)(nil).ToolError), msg)
}

// ToolOutput mocks base method.
func (m *MockIOInterface) ToolOutput(msg string, bold bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToolOutput", msg, bold)
}

// ToolOutput indicates an expected call of ToolOutput.
func (mr *MockIOInterfaceMockRecorder) ToolOutput(msg, bold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolOutput", reflect.TypeOf((*MockIOInterface)(nil).ToolOutput), msg, bold)
}

// ToolWarning mocks base method.
func (m *MockIOInterface) ToolWarning(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToolWarning", msg)
}

// ToolWarning indicates an expected call of ToolWarning.
func (mr *MockIOInterfaceMockRecorder) ToolWarning(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolWarning", reflect.TypeOf((*MockIOInterface)(nil).ToolWarning), msg)
}
